// SignIn
export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

// SignUp
export const SIGN_UP_START = "SIGN_UP_START"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"

// Logout
export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

// Favorites movie
export const FAVORITE_MOVIE_START = "FAVORITE_MOVIE_START"
export const FAVORITE_MOVIE_SUCCESS = "FAVORITE_MOVIE_SUCCESS"
export const FAVORITE_MOVIE_FAILURE = "FAVORITE_MOVIE_FAILURE"

// Watching
export const WATCHING_START = "WATCHING_START"
export const WATCHING_SUCCESS = "WATCHING_SUCCESS"
export const WATCHING_FAILURE = "WATCHING_FAILURE"

// Get movies favorite
export const GET_MOVIES_FAVORITE_START = "GET_MOVIES_FAVORITE_START"
export const GET_MOVIES_FAVORITE_SUCCESS = "GET_MOVIES_FAVORITE_SUCCESS"
export const GET_MOVIES_FAVORITE_FAILURE = "GET_MOVIES_FAVORITE_FAILURE"

// Get movies watching 
export const GET_MOVIES_WATCHING_START = "GET_MOVIES_WATCHING_START"
export const GET_MOVIES_WATCHING_SUCCESS = "GET_MOVIES_WATCHING_SUCCESS"
export const GET_MOVIES_WATCHING_FAILURE = "GET_MOVIES_WATCHING_FAILURE"