// Load list movie
export const GET_MOVIE_START = "GET_MOVIE_START"
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS"
export const GET_MOVIE_FAILURE = "GET_MOVIE_FAILURE"

// Get movie by category
export const GET_MOVIES_BY_CATEGORY_START = "GET_MOVIES_BY_CATEGORY_START"
export const GET_MOVIES_BY_CATEGORY_SUCCESS = "GET_MOVIES_BY_CATEGORY_SUCCESS"
export const GET_MOVIES_BY_CATEGORY_FAILURE = "GET_MOVIES_BY_CATEGORY_FAILURE"

// Detail movie
export const GET_DETAIL_MOVIE_START = "GET_DETAIL_MOVIE_START"
export const GET_DETAIL_MOVIE_SUCCESS = "GET_DETAIL_MOVIE_SUCCESS"
export const GET_DETAIL_MOVIE_FAILURE = "GET_DETAIL_MOVIE_FAILURE"

// Get link movie
export const GET_LINK_MOVIE_START = 'GET_LINK_MOVIE_START'
export const GET_LINK_MOVIE_SUCCESS = 'GET_LINK_MOVIE_SUCCESS'
export const GET_LINK_MOVIE_FAILURE = 'GET_LINK_MOVIE_FAILURE'

// Search movies
export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START'
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS'
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE'