// Load list movie
export const GET_MOVIE_START = "GET_MOVIE_START"
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS"
export const GET_MOVIE_FAILURE = "GET_MOVIE_FAILURE"

// Detail movie
export const GET_DETAIL_MOVIE_START = "GET_DETAIL_MOVIE_START"
export const GET_DETAIL_MOVIE_SUCCESS = "GET_DETAIL_MOVIE_SUCCESS"
export const GET_DETAIL_MOVIE_FAILURE = "GET_DETAIL_MOVIE_FAILURE"
